makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/

theme: jekyll-theme-cayman #jekyll-theme-slate

include:
  - assets
  - README.md
  - docs/*

title: [IoT-Würfel]
description: [Dokumentation zur Makecode Erweiterung IoT-Cube]
show_downloads: [false]

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  start_url: /lora-at-interface
  blocks_url: /lora-at-interface/docs/blocks
  examples_url: /lora-at-interface/docs/examples
  logic_url: /lora-at-interface/docs/program-logic