makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/

#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme


include: 
  - assets

title: IoT-Würfel
description: Dokumentation zur Makecode Erweiterung IoT-Cube
lang: de
show_downloads: [false]

plugins:
  - jekyll-remote-theme 
  - jekyll-github-metadata

github:
  start_url: /lora-at-interface
  blocks_url: /lora-at-interface/docs/blocks
  examples_url: /lora-at-interface/docs/examples
  logic_url: /lora-at-interface/docs/program-logic
